void fun(){
	throw new Exception(arguments[0]);
}

fun();